[project]
name = "ai-diary-backup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy",
    "fastapi",
    "uvicorn",
    "pydantic",
    "passlib>=1.7.4",
    "bcrypt>=4.3.0",
]
